language: generic
sudo: required
dist: trusty
services:
  - docker

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang

matrix:
  include:
    - os: linux
    - os: osx
      # Build on older OS X for more portable binaries
      osx_image: xcode6.4

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget --no-check-certificate https://cmake.org/files/v3.4/cmake-3.4.3-Darwin-x86_64.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then tar -xzf cmake-3.4.3-Darwin-x86_64.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=$PWD/cmake-3.4.3-Darwin-x86_64/CMake.app/Contents/bin:$PATH; fi

script:
  - mkdir -p target
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      make manylinux-wheels;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      sudo easy_install virtualenv;
      make mac-wheels;
    fi

deploy:
  provider: script
  script: .ci/deploy.sh
  skip_cleanup: true
  on:
    tags: true
