[package]
name = "libdebug"
version = "0.1.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]

[lib]
name = "libdebug"
crate-type = ["cdylib", "rlib"]

[dependencies]
gimli = "0.13.0"
memmap = "0"
uuid = "0.5"
mach_object = "0.1.5"
if_chain = "^0.1.2"
